[workspace]
members = ["emery", "omnia", "vectis", "specify"]
resolver = "3"

[workspace.package]
authors = ["Augentic"]
categories = ["development-tools", "wasm"]
edition = "2024"
homepage = "https://augentic.io"
keywords = ["agentic", "ai-assisted", "code-generation"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/augentic/crates-io"
rust-version = "1.91"
version = "0.1.0-alpha.1"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
